CREATE TABLE `user` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '唯一编号（自增）',
	`ENABLE` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '是否可用（1是 0否）',
	`CTIME` DATETIME NOT NULL COMMENT '记录创建时间',
	`MTIME` DATETIME NULL DEFAULT NULL COMMENT '修改时间',
	`NAME` VARCHAR(20) NOT NULL COMMENT '名字',
	`PASS_WORD` VARCHAR(100) NOT NULL COMMENT '密码',
	`PHONE` VARCHAR(20) NOT NULL COMMENT '手机',
	`EMAIL` VARCHAR(64) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `user_phone_index` (`PHONE`)
)
COMMENT='用户基本信息'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=66
;